services:
  postgres:
    container_name: "postgres"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - .env.development

  mailcatcher:
    container_name: "mailcatcher"
    image: "sj26/mailcatcher:v0.10.0"
    ports:
      - "1025:1025"
      - "1080:1080"

  app:
    image: node:24.13
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    command: tail -f /dev/null
    ports:
      - "3000:3000"
